-- Nimzo: exactly one room per owner; permanent room number = owner Nimzo ID.
-- Stage and test before production. No existing rooms, profiles, wallets or
-- ledger rows are modified by this migration.
--
-- Preconditions fail closed rather than deleting or renumbering rooms.
do $$
begin
  if exists (
    select 1 from public.rooms group by owner_id having count(*) > 1
  ) then
    raise exception 'Duplicate owner rooms exist; resolve manually before migration';
  end if;
  if exists (
    select 1 from public.rooms r
    join public.profiles p on p.id = r.owner_id
    where r.room_no is distinct from p.nimzo_id
  ) then
    raise exception 'Existing room number differs from owner Nimzo ID';
  end if;
end $$;

-- Enforce ownership at the database layer even under concurrent room creation.
alter table public.rooms
  add constraint rooms_one_per_owner unique (owner_id);

-- The identity column is GENERATED BY DEFAULT, so its value may be set in
-- a BEFORE trigger. This ensures all new rooms use the permanent user ID,
-- including callers that omit room_no.
create or replace function public.nimzo_enforce_owner_room_number()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  owner_number bigint;
begin
  if new.owner_id is null then
    raise exception 'Room owner is required';
  end if;

  select p.nimzo_id into owner_number
  from public.profiles p where p.id = new.owner_id;

  if owner_number is null then
    raise exception 'Room owner profile does not exist';
  end if;

  new.room_no := owner_number;
  return new;
end;
$$;

revoke all on function public.nimzo_enforce_owner_room_number() from public;
revoke all on function public.nimzo_enforce_owner_room_number() from anon;
revoke all on function public.nimzo_enforce_owner_room_number() from authenticated;

create trigger nimzo_room_owner_number_guard
before insert or update of owner_id, room_no on public.rooms
for each row
execute function public.nimzo_enforce_owner_room_number();

-- Verify the existing create-room RPC handles unique_violation and returns
-- the owner's existing room, rather than surfacing a raw database error.
-- A unique owner constraint is intentional for closed rooms too.
